# Site settings
title: Lukin
email: maarten@lukin.be
description: > # this means to ignore newlines until "baseurl:"
  Hello World
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lukin.be" # the base hostname & protocol for your site
twitter_username: lukin0110
github_username:  lukin0110

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed
